basePath: /api/v1
definitions:
  dto.OuterService:
    properties:
      link:
        type: string
      name:
        type: string
    type: object
  models.OuterService:
    properties:
      id:
        type: integer
      link:
        description: '@description: Link is a link to the implementation of the service.'
        type: string
      name:
        type: string
    type: object
  responses.ErrorResp:
    properties:
      description:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  responses.HealthSuccess:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
  responses.ServiceCreated:
    properties:
      id:
        type: integer
    type: object
  responses.Services:
    properties:
      services:
        items:
          $ref: '#/definitions/models.OuterService'
        type: array
    type: object
host: localhost:80
info:
  contact:
    name: Artyom Fadeyev
    url: https://github.com/fadyat
  description: This is a sample server for a balance API.
  title: Avito Internship 2022 Balance API
  version: 1.0.0
paths:
  /api/v1/health:
    get:
      description: Healthcheck endpoint, that checks if the service is alive and database
        connection is working.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResp'
      summary: Healthcheck
      tags:
      - health
  /api/v1/service:
    get:
      description: Get all outer services info in the system
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Services'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResp'
      summary: Get all services
      tags:
      - OuterService
    post:
      description: Create new outer service info in the system
      parameters:
      - description: Outer service short info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.OuterService'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.ServiceCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResp'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResp'
      summary: New service
      tags:
      - OuterService
  /api/v1/service/{id}:
    get:
      description: Get outer service info in the system by id
      parameters:
      - description: service_id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OuterService'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResp'
      summary: Get service by id
      tags:
      - OuterService
schemes:
- http
swagger: "2.0"
