basePath: /api/v1
definitions:
  dto.OuterService:
    properties:
      link:
        type: string
      name:
        type: string
    type: object
  responses.HealthError:
    properties:
      description:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  responses.HealthSuccess:
    properties:
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:80
info:
  contact:
    name: Artyom Fadeyev
    url: https://github.com/fadyat
  description: This is a sample server for a balance API.
  title: Avito Internship 2022 Balance API
  version: 1.0.0
paths:
  /api/v1/health:
    get:
      description: Healthcheck endpoint, that checks if the service is alive and database
        connection is working.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.HealthError'
      summary: Healthcheck
      tags:
      - health
  /api/v1/service:
    get:
      description: Get all outer services info in the system
      responses: {}
      summary: Get all services
      tags:
      - OuterService
    post:
      description: Create new outer service info in the system
      parameters:
      - description: Outer service info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.OuterService'
      responses: {}
      summary: New service
      tags:
      - OuterService
  /api/v1/service/{id}:
    get:
      description: Get outer service info in the system by id
      parameters:
      - description: Service id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Get service by id
      tags:
      - OuterService
schemes:
- http
swagger: "2.0"
